In [28]:
#importing important libraries 
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error 

In [2]:
#reading the csv file
df = pd.read_csv(r'D:\\jeshmi\\csv_files\\Real estate1.csv')

In [3]:
#displaying the csv file
df

No  X1 transaction date  distance       store  age  latitude  longitude  \
0    1             2012.917      32.0    84.87882   10  24.98298  121.54024   
1    2             2012.917      19.5   306.59470    9  24.98034  121.53951   
2    3             2013.583      13.3   561.98450    5  24.98746  121.54391   
3    4             2013.500      13.3   561.98450    5  24.98746  121.54391   
4    5             2012.833       5.0   390.56840    5  24.97937  121.54245   
5    6             2012.667       7.1  2175.03000    3  24.96305  121.51254   
6    7             2012.667      34.5   623.47310    7  24.97933  121.53642   
7    8             2013.417      20.3   287.60250    6  24.98042  121.54228   
8    9             2013.500      31.7  5512.03800    1  24.95095  121.48458   
9   10             2013.417      17.9  1783.18000    3  24.96731  121.51486   
10  11             2013.083      34.8   405.21340    1  24.97349  121.53372   
11  12             2013.333       6.3    90.45606    9  24.97433  121.54310   
12  13             2012.917      13.0   492.23130    5  24.96515  121.53737   
13  14             2012.667      20.4  2469.64500    4  24.96108  121.51046   
14  15             2013.500      13.2  1164.83800    4  24.99156  121.53406   
15  16             2013.583      35.7   579.20830    2  24.98240  121.54619   
16  17             2013.250       0.0   292.99780    6  24.97744  121.54458   
17  18             2012.750      17.7   350.85150    1  24.97544  121.53119   
18  19             2013.417      16.9   368.13630    8  24.96750  121.54451   
19  20             2012.667       1.5    23.38284    7  24.96772  121.54102   

    areaprice  
0        37.9  
1        42.2  
2        47.3  
3        54.8  
4        43.1  
5        32.1  
6        40.3  
7        46.7  
8        18.8  
9        22.1  
10       41.4  
11       58.1  
12       39.3  
13       23.8  
14       34.3  
15       50.5  
16       70.1  
17       37.4  
18       42.3  
19       47.7

In [4]:
final = df.drop(['X1 transaction date'],axis = 1)

In [5]:
final

No  distance       store  age  latitude  longitude  areaprice
0    1      32.0    84.87882   10  24.98298  121.54024       37.9
1    2      19.5   306.59470    9  24.98034  121.53951       42.2
2    3      13.3   561.98450    5  24.98746  121.54391       47.3
3    4      13.3   561.98450    5  24.98746  121.54391       54.8
4    5       5.0   390.56840    5  24.97937  121.54245       43.1
5    6       7.1  2175.03000    3  24.96305  121.51254       32.1
6    7      34.5   623.47310    7  24.97933  121.53642       40.3
7    8      20.3   287.60250    6  24.98042  121.54228       46.7
8    9      31.7  5512.03800    1  24.95095  121.48458       18.8
9   10      17.9  1783.18000    3  24.96731  121.51486       22.1
10  11      34.8   405.21340    1  24.97349  121.53372       41.4
11  12       6.3    90.45606    9  24.97433  121.54310       58.1
12  13      13.0   492.23130    5  24.96515  121.53737       39.3
13  14      20.4  2469.64500    4  24.96108  121.51046       23.8
14  15      13.2  1164.83800    4  24.99156  121.53406       34.3
15  16      35.7   579.20830    2  24.98240  121.54619       50.5
16  17       0.0   292.99780    6  24.97744  121.54458       70.1
17  18      17.7   350.85150    1  24.97544  121.53119       37.4
18  19      16.9   368.13630    8  24.96750  121.54451       42.3
19  20       1.5    23.38284    7  24.96772  121.54102       47.7

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['distance','store','age','latitude','longitude']],df.areaprice)

LinearRegression()

In [7]:
#calculating m
reg.coef_ 

array([-2.45005758e-01,  6.65404250e-03, -3.19711965e-01, -1.75332631e+02,
        1.20445128e+03])

In [8]:
#calculating b
reg.intercept_

-141960.8068091344

In [9]:
reg.predict([[40.0,456,10,24.96,121.54]])

array([41.93604436])

In [10]:
#implementing the y=mx+c formula
-2.45005758e-01*40.0+6.65404250e-03*456+(-3.19711965e-01)*10+(-1.75332631e+02)*24.96+1.20445128e+03*121.54+(-141960.8068091344)

41.93618571560364

In [11]:
df.shape

(20, 8)

In [19]:
#Calculation of mean squared Error starts from here
y_pred = reg.predict(df[['distance','store','age','latitude','longitude']])

In [20]:
y_pred

array([37.68655878, 42.12777832, 50.67625376, 50.67625376, 51.22913365,
       30.0642196 , 37.65596972, 46.08683813, 15.32616201, 26.85818082,
       35.82035458, 49.30138783, 46.32017435, 26.2864584 , 42.44917023,
       49.8952006 , 54.38908476, 36.25906628, 51.76753305, 49.32422137])

In [23]:
#sum of squares
sse = (df['areaprice'] - y_pred)**2

In [24]:
sse

0       0.045557
1       0.005216
2      11.399089
3      17.005283
4      66.082814
5       4.144402
6       6.990896
7       0.375967
8      12.067550
9      22.640285
10     31.132443
11     77.415576
12     49.282848
13      6.182475
14     66.408975
15      0.365782
16    246.832858
17      1.301730
18     89.634182
19      2.638095
Name: areaprice, dtype: float64

In [26]:
#mean of sum of squares
mse = np.mean(sse)

In [27]:
#Finally, mean sqaured error calculated
mse

35.597601243286235

In [30]:
mean_squared_error(df['areaprice'],y_pred)

35.597601243286235